create table if not exists public.leaderboard_entries (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default timezone('utc', now()),
  display_name text not null check (char_length(display_name) between 1 and 32),
  score integer not null check (score >= 0),
  accuracy integer not null check (accuracy between 0 and 100),
  correct_answers integer not null check (correct_answers >= 0),
  total_rounds integer not null check (total_rounds > 0),
  round_count integer not null check (round_count in (5, 10, 15, 20)),
  source_type text not null check (source_type in ('artist', 'playlist')),
  source_id text not null,
  source_name text not null
);

alter table public.leaderboard_entries
  add column if not exists round_count integer;

update public.leaderboard_entries
set round_count = total_rounds
where round_count is null;

alter table public.leaderboard_entries
  alter column round_count set not null;

create index if not exists leaderboard_entries_lookup_idx
  on public.leaderboard_entries (source_type, source_id, round_count, score desc, accuracy desc, created_at asc);

alter table public.leaderboard_entries enable row level security;

drop policy if exists "anon can read leaderboard entries" on public.leaderboard_entries;
create policy "anon can read leaderboard entries"
  on public.leaderboard_entries
  for select
  to anon
  using (true);

drop policy if exists "anon can insert leaderboard entries" on public.leaderboard_entries;
create policy "anon can insert leaderboard entries"
  on public.leaderboard_entries
  for insert
  to anon
  with check (true);
